####
# This Dockerfile is used with render.com as they don't allow to deploy images straight from a registry
#
###
#FROM gunnarmorling/quarkus-on-render:latest

# Use this for the first deployment on Render
#FROM mrmos/hello_nginx:latest

FROM mrmos/quarkus-on-render:latest